btcven/turpial-firmware

- platformio.ini
- src/hal/esp32_wemos.h
- src/hal/hardware.h
add new board definition named esp32 wemosbat
> add new board esp32 wemos

- CONTRIBUTING.md
> add contributing doc link

- test/TestSerializablePOD.cpp
- test/serializable_pod_tests.cpp
> [WIP] Add unit tests

- include/WiFiDTO.h
- lib/Serializable/src/Serializable.h
- lib/SerializablePOD/src/SerializablePOD.h
- src/main.cpp
- src/testRTOSCPP/Hello.hpp
See more: [`<cstdint> vs <stdint.h>`](https://stackoverflow.com/questions/13642827/cstdint-vs-stdint-h)
> use c* headers in C++ code for C headers

- lib/SerializablePOD/src/SerializablePOD.h
> [WIP] Changes to feature/nvs

- .gitignore
- doc/Makefile
- doc/conf.py
- doc/index.rst
- doc/make.bat
Sphinx can be used now to generate the project's documentation.
> Use Sphinx to generate project documentation

- lib/TinyString/src/TinyString.h
`tinystring::String` now uses a `std::string` internally for safety purposes
and to solve the bug related to assignation.
> use std::string internally instead of char*

- test/test_nvs/test_nvs.cpp
> fix nvs unit test

- components/ESC/src/FuelGauge.h
- components/NVS/src/Storage.cpp
Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>
> Remove extra spaces.

- components/ESC/src/Battery.cpp
- components/ESC/src/Battery.h
- main/defaults.h
- main/main.cpp
Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>
> ESC: set SYSOFF to 0

- .travis.yml
- CONTRIBUTING.md
- components/BLE/src/Advertising.h
- components/BLE/src/Characteristic.h
- components/NVS/src/Storage.cpp
- components/NVS/src/Storage.h
- components/Network/src/WiFi.h
- components/Task/src/Task.cpp
- components/WS/src/HttpServer.cpp
- components/WS/src/WsHandlerEvents.h
- main/main.cpp
- test/CMakeLists.txt
- test/test_gpio/test_gpio.cpp
Fixed some misspelling found by codespell:
https://travis-ci.com/btcven/turpial-firmware/jobs/291928671#L698
> Fix some misspelling

- components/HTTP/src/HttpServerHandler.cpp
- components/Network/src/WiFi.cpp
- components/Network/src/WiFi.h
- components/Network/src/WiFiEventHandler.cpp
- components/Network/src/WiFiEventHandler.h
> components: fix HTTP, Network warnings

- components/HTTP/CMakeLists.txt
- components/HTTP/src/RESTServer.cpp
- components/HTTP/src/Websocket.cpp
- components/HTTP/src/Websocket.h
- components/Util/CMakeLists.txt
- components/Util/src/Serialization.cpp
- components/Util/src/Serialization.h
The data serialization functions were added that will be sent through the radio module.
> added serialization functions

- .travis.yml
Please review ASAP. The commit is outdated and doesn't compiles.
> traivs: update esp-idf commit.

- components/HMI/src/HumanInterface.cpp
- components/HMI/src/HumanInterface.h
- components/HMI/src/UserButton.cpp
- components/HMI/src/UserButtonHandler.cpp
- components/HTTP/src/Websocket.cpp
- components/Network/src/WiFi.cpp
- components/Util/src/Base64.cpp
- components/Util/src/Serialization.cpp
Please review ASAP. Build is failing on `dev` due to missing code. Some unrelated warnings were fixed.
> components: fix warnings and errors

- components/HTTP/src/HttpServer.cpp
- components/HTTP/src/HttpServer.h
- components/HTTP/src/RESTServer.cpp
- components/HTTP/test/CMakeLists.txt
- components/HTTP/test/testHttpServer.cpp
- test/sdkconfig.defaults
unit test aggregates in http component
> 2020 04 16 test http

- components/HTTP/src/RESTServer.cpp
- components/HTTP/src/Websocket.cpp
- components/HTTP/src/Websocket.h
- components/Radio/src/Radio.cpp
- components/Radio/src/Radio.h
- main/main.cpp
_Work in progress_, feedback is welcome.
> components/HTTP: chat uart communication

- components/HTTP/src/Websocket.cpp
- components/HTTP/src/Websocket.h
- main/main.cpp
work in progress missing order code
> 2020 04 20 decode message

- components/HTTP/src/Websocket.cpp
- components/HTTP/src/Websocket.h
- components/Radio/CMakeLists.txt
- components/Radio/src/Radio.cpp
- components/Radio/src/Radio.h
- components/Util/src/Hex.cpp
- main/main.cpp
Is worked on, needs rebase. Comments are appreciated please on any error.
> chat: uart RX

- components/HTTP/src/Message.cpp
- components/HTTP/src/Message.h
- components/HTTP/src/Websocket.cpp
- components/HTTP/src/Websocket.h
The functions of the websocket message have been moved, if you have any recommendations it is welcome.
> separate message functions of the websocket class

- components/HTTP/src/RESTServer.cpp
- components/HTTP/src/Websocket.cpp
- components/NVS/src/Credentials.cpp
- components/NVS/src/Credentials.h
- components/NVS/src/Storage.cpp
- components/NVS/src/Storage.h
- main/main.cpp
work in progress, need to add the username and password change, comments are welcome.
> 2020 04 27 https autentication

- components/HTTP/src/RESTServer.cpp
- main/Kconfig.projbuild
- main/defaults.h
- main/main.cpp
Currently only configuration for device name/version and ESC are there,
this is the base to migrate other code to Kconfig.
> add basic Kconfig file

- components/ESC/src/FuelGauge.cpp
- components/HMI/src/HumanInterface.cpp
- components/HMI/src/HumanInterface.h
- components/HMI/src/UserButton.cpp
- components/HTTP/src/HttpServer.cpp
- components/HTTP/src/RESTServer.cpp
- components/HTTP/src/Websocket.cpp
- components/NVS/src/Credentials.cpp
- components/Network/src/WiFi.cpp
- components/Radio/src/Radio.cpp
this PR completes the code revision of issue #139
> Verify that we comply with the coding style

- components/HTTP/src/HttpServer.h
> removed macro in httpServer.h

- components/Network/CMakeLists.txt
- components/Network/src/WiFi.cpp
- components/Network/src/WiFi.h
- components/Network/src/WiFiEventHandler.cpp
- components/Util/src/Hex.cpp
- components/Util/src/Hex.h
- components/VAINA/CMakeLists.txt
- components/VAINA/src/Vaina.cpp
- components/VAINA/src/Vaina.h
- main/CMakeLists.txt
- main/main.cpp
added part of VAINA component functionality.
> components: add vaina component

- components/HTTP/src/RESTServer.cpp
- components/Network/CMakeLists.txt
- components/Network/Kconfig
- components/Network/include/Network/Network.h
- components/Network/include/Network/Slip.h
- components/Network/include/Network/WiFi.h
- components/Network/include/Network/WiFiEventHandler.h
- components/Network/src/Network.cpp
- components/Network/src/Slip.cpp
- components/Network/src/WiFi.cpp
- components/Network/src/WiFiEventHandler.cpp
- components/Network/test/TestWiFi.cpp
- components/VAINA/src/Vaina.h
- main/Kconfig.projbuild
- main/main.cpp
This is a refactor to the network interfaces. This makes them more accesible, there are things to do as moving the WiFi configuration code (needs to be reworked), this is the start of the refactoring.
This is needed as we need a way to access each interface manually if we want to send packets over specific interfaces.
> components/Network: refactor network interfaces.

- Makefile
- main.c
- sys/Makefile
- sys/Makefile.dep
- sys/Makefile.include
- sys/include/net/vaina.h
- sys/net/Makefile
- sys/net/vaina/Kconfig
- sys/net/vaina/Makefile
- sys/net/vaina/vaina.c
This implements a basic client for the VAINA server, is still being worked.
> turpial-firmware: add vaina module

- Makefile
- main.c
- sys/Makefile
- sys/Makefile.dep
- sys/Makefile.include
- sys/include/net/vaina.h
- sys/include/storage/nvs.h
- sys/net/Makefile
- sys/net/vaina/Kconfig
- sys/net/vaina/Makefile
- sys/net/vaina/vaina.c
- sys/storage/Makefile
- sys/storage/nvs/Makefile
- sys/storage/nvs/nvs.c
This branch was taken from the pr #165 where the structure of the components was already defined.
in this pr the nvs module is added
> add nvs module

- README.md
Signed-off-by: Jean Pierre Dudey <me@jeandudey.tech>
> README: update the bird
